version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_network

networks:
  django_network:

volumes:
  postgres_data:
  static_volume:
