# Generated by Django 5.1.3 on 2024-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, null=True),
        ),
    ]
