# Generated by Django 5.1.3 on 2024-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='requested', max_length=20)),
                ('currency_pair', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
    ]
